export const BANNED_WORDS = [
    'negro',
    'nègre',
    'negre',
    'nègré',
    'negré',
    'nigger',
    'nigga',
    'niga',
    'n1gger',
    'n1gga',
    'n1ga',
    'n*gger',
    'n*gga',
    'bougnoule',
    'bougnoul',
    'boug noule',
    'boug-noule',
    'bougn0ule',
    'b0ugnoule',
    'bamboula',
    'bamboula',
    'bam boula',
    'bam-boula',
    'chinetoque',
    'chinetok',
    'chine toque',
    'chine-toque',
    'ch1netoque',
    'raton',
    'ra ton',
    'ra-ton',
    'youpin',
    'you pin',
    'you-pin',
    'pd',
    'p d',
    'p-d',
    'pédé',
    'pede',
    'pé dé',
    'pe de',
    'pé-dé',
    'pe-de',
    'p3dé',
    'p3de',
    'pédale',
    'pedale',
    'pé dale',
    'pe dale',
    'pé-dale',
    'pe-dale',
    'tapette',
    'ta pette',
    'ta-pette',
    't4pette',
    'gouine',
    'gou ine',
    'gou-ine',
    'fiotte',
    'fi otte',
    'fi-otte',
    'enculé',
    'encule',
    'en culé',
    'en cule',
    'en-culé',
    'en-cule',
    'enculée',
    'enculee',
    'en culée',
    'en culee',
    'en-culée',
    'en-culee',
    '3nculé',
    '3ncule',
    'salope',
    'sa lope',
    'sa-lope',
    's4lope',
    'pute',
    'pu te',
    'pu-te',
    'putain',
    'pu tain',
    'pu-tain',
    'put4in',
    'connard',
    'con nard',
    'con-nard',
    'c0nnard',
    'connasse',
    'con nasse',
    'con-nasse',
    'c0nnasse',
    'conne',
    'con ne',
    'con-ne',
    'con',
    'c0n',
    'salaud',
    'sa laud',
    'sa-laud',
    'bâtard',
    'batard',
    'bâ tard',
    'ba tard',
    'bâ-tard',
    'ba-tard',
    'enfoiré',
    'enfoire',
    'en foiré',
    'en foire',
    'en-foiré',
    'en-foire',
    'merde',
    'mer de',
    'mer-de',
    'm3rde',
    'bordel',
    'bor del',
    'bor-del',
    'foutre',
    'fou tre',
    'fou-tre',
    'nique',
    'ni que',
    'ni-que',
    'n1que',
    'ntm',
    'n t m',
    'n-t-m',
    'nique ta mère',
    'nique ta mere',
    'nique-ta-mère',
    'nique-ta-mere',
    'niqueta mère',
    'niquetamère',
    'niquetamere',
    'nique ta race',
    'nique-ta-race',
    'niquetarace',
    'fils de pute',
    'filsdepute',
    'fils-de-pute',
    'fdp',
    'f d p',
    'f-d-p',
    'salopard',
    'sa lopard',
    'sa-lopard',
    'pétasse',
    'petasse',
    'pé tasse',
    'pe tasse',
    'pé-tasse',
    'pe-tasse',
    'pouffiasse',
    'pouffi asse',
    'pouffi-asse',
    'chienne',
    'chien ne',
    'chien-ne',
    'trou du cul',
    'trouducul',
    'trou-du-cul',
    'tdc',
    't d c',
    't-d-c',
    'cul',
    'c ul',
    'c-ul',
    'bite',
    'bi te',
    'bi-te',
    'b1te',
    'chatte',
    'cha tte',
    'cha-tte',
    'couilles',
    'cou illes',
    'cou-illes',
    'branleur',
    'bran leur',
    'bran-leur',
    'suceur',
    'su ceur',
    'su-ceur',
    'suce',
    'su ce',
    'su-ce',
    'fuck',
    'f uck',
    'f-uck',
    'f*ck',
    'fuk',
    'fucking',
    'fuckin',
    'shit',
    'sh it',
    'sh-it',
    'sh1t',
    'asshole',
    'ass hole',
    'ass-hole',
    'a$$hole',
    'ass',
    'a ss',
    'a-ss',
    'bitch',
    'bi tch',
    'bi-tch',
    'b1tch',
    'bastard',
    'bas tard',
    'bas-tard',
    'cunt',
    'cu nt',
    'cu-nt',
    'dick',
    'di ck',
    'di-ck',
    'd1ck',
    'pussy',
    'pus sy',
    'pus-sy',
    'faggot',
    'fag got',
    'fag-got',
    'f4ggot',
    'fag',
    'f ag',
    'f-ag',
    'retard',
    're tard',
    're-tard',
    'r3tard',
    'retarded',
    'mongol',
    'mon gol',
    'mon-gol',
    'attardé',
    'attarde',
    'at tardé',
    'at tarde',
    'at-tardé',
    'at-tarde',
    'débile',
    'debile',
    'dé bile',
    'de bile',
    'dé-bile',
    'de-bile',
    'sous-merde',
    'sous merde',
    'sousmerde',
    'gros con',
    'groscon',
    'gros-con',
    'sale con',
    'salecon',
    'sale-con',
    'va te faire foutre',
    'vatefairefoutre',
    'va-te-faire-foutre',
    'vtff',
    'v t f f',
    'v-t-f-f',
    'ntr',
    'n t r',
    'n-t-r',
    'kys',
    'k y s',
    'k-y-s',
    'kill yourself',
    'killyourself',
    'kill-yourself',
    'suicide',
    'sui cide',
    'sui-cide',
    'ta gueule',
    'tagueule',
    'ta-gueule',
    'tg',
    't g',
    't-g',
    'ftg',
    'f t g',
    'f-t-g',
    'ferme ta gueule',
    'fermetagueule',
    'ferme-ta-gueule',
    'nique toi',
    'niqueto i',
    'nique-toi',
    'ntm',
    'ntmére',
    'ntmere',
    'fdpute',
    'filsdepute',
    'enculer',
    'en culer',
    'en-culer',
    'enculeur',
    'en culeur',
    'en-culeur',
    'saloperie',
    'sa loperie',
    'sa-loperie',
    'putain de merde',
    'putaindemerde',
    'putain-de-merde',
    'bordel de merde',
    'bordeldemerde',
    'bordel-de-merde',
    'fils de chien',
    'filsdechien',
    'fils-de-chien',
    'race de chien',
    'racedechien',
    'race-de-chien',
    'enfoiré de merde',
    'enfoiredemerde',
    'enfoiré-de-merde',
    'connard de merde',
    'connarddemerde',
    'connard-de-merde',
    'sale pute',
    'salepute',
    'sale-pute',
    'grosse pute',
    'grossepute',
    'grosse-pute',
    'petite pute',
    'petitepute',
    'petite-pute',
    'sale salope',
    'salesalope',
    'sale-salope',
    'grosse salope',
    'grossesalope',
    'grosse-salope',
    'enculé de ta mère',
    'enculedetamère',
    'enculé-de-ta-mère',
    'enculé de ta race',
    'enculedetarace',
    'enculé-de-ta-race',
    'nique ta mère la pute',
    'niquetamèrelapute',
    'nique-ta-mère-la-pute',
    'ta mère la pute',
    'tamèrelapute',
    'ta-mère-la-pute',
    'ta mere la pute',
    'tamerelapute',
    'ta-mere-la-pute',
    'ta race',
    'tarace',
    'ta-race',
    'nique sa mère',
    'niquesamère',
    'nique-sa-mère',
    'nique sa mere',
    'niquesamere',
    'nique-sa-mere',
    'fils de ta mère',
    'filsdetamère',
    'fils-de-ta-mère',
    'fils de ta mere',
    'filsdetamere',
    'fils-de-ta-mere',
    'enculé de tes morts',
    'enculedetesmorts',
    'enculé-de-tes-morts',
    'nique tes morts',
    'niquetesmorts',
    'nique-tes-morts',
    'ntm les morts',
    'ntmlesmorts',
    'ntm-les-morts',
    'fdp de merde',
    'fdpdemerde',
    'fdp-de-merde',
    'pd de merde',
    'pddemerde',
    'pd-de-merde',
    'sale pd',
    'salepd',
    'sale-pd',
    'gros pd',
    'grospd',
    'gros-pd',
    'petit pd',
    'petitpd',
    'petit-pd',
    'sale pédé',
    'salepédé',
    'sale-pédé',
    'sale pede',
    'salepede',
    'sale-pede',
    'gros pédé',
    'grospédé',
    'gros-pédé',
    'gros pede',
    'grospede',
    'gros-pede',
    'sale enculé',
    'saleenculé',
    'sale-enculé',
    'sale encule',
    'saleencule',
    'sale-encule',
    'gros enculé',
    'grosenculé',
    'gros-enculé',
    'gros encule',
    'grosencule',
    'gros-encule',
    'sale connard',
    'saleconnard',
    'sale-connard',
    'gros connard',
    'grosconnard',
    'gros-connard',
    'sale connasse',
    'saleconnasse',
    'sale-connasse',
    'grosse connasse',
    'grosseconnasse',
    'grosse-connasse',
    'sale bâtard',
    'salebâtard',
    'sale-bâtard',
    'sale batard',
    'salebatard',
    'sale-batard',
    'gros bâtard',
    'grosbâtard',
    'gros-bâtard',
    'gros batard',
    'grosbatard',
    'gros-batard',
    'sale enfoiré',
    'saleenfoiré',
    'sale-enfoiré',
    'sale enfoire',
    'saleenfoire',
    'sale-enfoire',
    'gros enfoiré',
    'grosenfoiré',
    'gros-enfoiré',
    'gros enfoire',
    'grosenfoire',
    'gros-enfoire',
    'merde alors',
    'merdealors',
    'merde-alors',
    'putain de bordel',
    'putaindebordel',
    'putain-de-bordel',
    'bordel de putain',
    'bordeldeputain',
    'bordel-de-putain',
    'fuck you',
    'fuckyou',
    'fuck-you',
    'fuck u',
    'fucku',
    'fuck-u',
    'shit head',
    'shithead',
    'shit-head',
    'ass hole',
    'asshole',
    'ass-hole',
    'dumb ass',
    'dumbass',
    'dumb-ass',
    'mother fucker',
    'motherfucker',
    'mother-fucker',
    'mthfckr',
    'mf',
    'm f',
    'm-f',
    'son of a bitch',
    'sonofabitch',
    'son-of-a-bitch',
    'sob',
    's o b',
    's-o-b',
    'bitch ass',
    'bitchass',
    'bitch-ass',
    'dick head',
    'dickhead',
    'dick-head',
    'cock sucker',
    'cocksucker',
    'cock-sucker',
    'pussy licker',
    'pussylicker',
    'pussy-licker',
    'faggot ass',
    'faggotass',
    'faggot-ass',
    'retard ass',
    'retardass',
    'retard-ass',
    'nigger lover',
    'niggerlover',
    'nigger-lover',
    'white trash',
    'whitetrash',
    'white-trash',
    'black monkey',
    'blackmonkey',
    'black-monkey',
    'sale nègre',
    'salenègre',
    'sale-nègre',
    'sale negre',
    'salenegre',
    'sale-negre',
    'gros nègre',
    'grosnègre',
    'gros-nègre',
    'gros negre',
    'grosnegre',
    'gros-negre',
    'sale negro',
    'salenegro',
    'sale-negro',
    'gros negro',
    'grosnegro',
    'gros-negro',
    'sale bougnoule',
    'salebougnoule',
    'sale-bougnoule',
    'gros bougnoule',
    'grosbougnoule',
    'gros-bougnoule',
    'sale chinetoque',
    'salechinetoque',
    'sale-chinetoque',
    'gros chinetoque',
    'groschinetoque',
    'gros-chinetoque',
    'sale raton',
    'saleraton',
    'sale-raton',
    'gros raton',
    'grosraton',
    'gros-raton',
];